 <header id="masthead" class="site-header" itemscope itemtype="http://schema.org/WPHeader">      
        <div class="pre-header">
            <div class="container-xl">
                <div class="row no-gutters d-flex justify-content-end">
                    <div class="col header-search ps-xl-0">
                        <form action="/" method="get">
    <input type="text" name="s" id="search" class="form-control" value="" placeholder="Search in the catalog">
    <input type="image" onclick="this.form.submit()" class="d-none" src="https://www.designparquet.com/wp-content/themes/designparquet/dist/img/icon-search.svg" class="img-submit" name="submit" alt="Rechercher">
</form>                    </div>
                    <div class="col-auto pe-0">
                        <div class="navigation">
                                                    <nav id="nav-pre-header" class="navigation__menu" aria-label="Menu pre-header">
                                <div class="menu-pre-header-menu-en-container"><ul id="pre-header-menu" class="menu"><li id="menu-item-4086" class="item-darken item-search menu-item menu-item-type-custom menu-item-object-custom menu-item-4086"><a href="#">Search</a></li>
<li id="menu-item-4087" class="pro menu-item menu-item-type-custom menu-item-object-custom menu-item-4087"><a target="_blank" rel="noopener" href="http://client.designparquet.com/consulter/default.asp?LangueID=2">Pro area</a></li>
<li id="menu-item-7998" class="item-darken item-contact menu-item menu-item-type-post_type menu-item-object-page menu-item-7998"><a href="https://dmafloors.com/contact-us/">Contact us</a></li>
<li class="menu-item lang-tag"><a href="https://www.designparquet.com/">fr</a></li><li class="menu-item lang-tag current-lang-item"><a href="https://dmafloors.com/">en</a></li></ul></div>                            </nav>
                                                </div>
                    </div>
                </div>

                <div class="row d-flex justify-content-start">
                    <div id="header-search-result" class="header-search-result list-group" role="search">
                        <div id="suggestions-results"></div>
                                                <div id="more-results" class="text-center"><a href="https://www.designparquet.com" id="search-all-link" class="btn btn-light rounded-bottom">See All</a></div>
                    </div>
                </div>

            </div>
        </div>

        <div class="header-dk d-none">
            <div class="container-xl">
                <div class="row no-gutters align-items-center d-flex">

                    <div class="col header-sp__action js-open-menu order-1 d-flex d-lg-none">
                        <div class="header-sp__action__open-menu">
                            <span></span>
                        </div>
                    </div>

                    <div class="col order-2 order-lg-1">
                        <a href="https://dmafloors.com/" class="header-logo-link ps-2 ps-xl-0" title="en Accéder à la page d'accueil"><img width="144" height="48" src="https://www.designparquet.com/wp-content/themes/designparquet/dist/img/logo-design-parquet.svg" alt="Design Parquet" class="logo" /></a>
                        <div class="site-title d-none d-lg-block">Manufacturer of custom-made parquet</div>
                    </div>
                    <div class="col float-right d-none d-lg-block order-3 order-lg-2">
                                            </div>
                    <div class="col order-3 order-lg-3">
                        <div class="navigation">
                                                    <nav id="nav-account" class="navigation__menu" aria-label="Menu account">
                                <div class="menu-professional-area-container"><ul id="account-menu" class="menu"><li id="menu-item-4084" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4084"><a target="_blank" rel="noopener" href="http://www.designparquet.fr/consulter/PagePerso.asp?LangueID=1&#038;IsMenuHaut=1&#038;PagePersoID=25648">Professional area</a></li>
</ul></div>                            </nav>
                                                                                </div>
                       
                    </div>
                </div>
            </div>
        </div>

        <div class="header-navigation shadow" id="navbar-top">
                        <nav class="navbar navbar-expand-md navbar-light bg-light justify-content-start flex-fill py-0">
                <div class="container-xl px-xl-0">  
                    <a href="https://dmafloors.com/" class="navbar-brand" title="Retourner à la page d'accueil"><img width="144" height="48" src="https://www.designparquet.com/wp-content/themes/designparquet/dist/img/logo-design-parquet.svg" alt="Design Parquet" class="logo" /></a>
                    <div id="main_nav" class="collapse navbar-collapse"><ul id="primary-mega-menu" class=" d-none d-md-flex justify-content-between w-100 flex-fill navbar-nav mr-auto" itemscope itemtype="http://www.schema.org/SiteNavigationElement"><li  id="menu-item-4100" class="menu-item menu-item-type-post_type_archive menu-item-object-parquet menu-item-has-children dropdown has-megamenu menu-item-4100 nav-item"><a href="#" data-bs-toggle="dropdown" aria-expanded="false" class="dropdown-toggle nav-link" id="menu-item-dropdown-4100"><span itemprop="name">Our Parquets</span></a>
<ul class="dropdown-menu megamenu depth-0" aria-labelledby="menu-item-dropdown-4100">
	<li  id="menu-item-4105" class="see-all menu-item menu-item-type-post_type_archive menu-item-object-parquet menu-item-has-children dropdown has-megamenu menu-item-4105 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/" class="dropdown-item"><span itemprop="name">COLORS</span><span class="see-all-link"> See All</span></a>
	<ul class="megamenu-child-col depth-1" aria-labelledby="menu-item-dropdown-4100">
		<li  id="menu-item-5110" class="menu-item menu-item-type-taxonomy menu-item-object-couleur-parquet menu-item-5110 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/color/natural/" class="dropdown-item"> <span class="menu-item-img"><img width="60" height="60" src="https://www.designparquet.com/wp-content/uploads/naturel.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Natural Parquet</span></a></li>
		<li  id="menu-item-5108" class="menu-item menu-item-type-taxonomy menu-item-object-couleur-parquet menu-item-5108 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/color/brown/" class="dropdown-item"> <span class="menu-item-img"><img width="60" height="60" src="https://www.designparquet.com/wp-content/uploads/marron.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Brown Parquet</span></a></li>
		<li  id="menu-item-5111" class="menu-item menu-item-type-taxonomy menu-item-object-couleur-parquet menu-item-5111 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/color/white/" class="dropdown-item"> <span class="menu-item-img"><img width="60" height="60" src="https://www.designparquet.com/wp-content/uploads/blanc.jpg" class="rounded-circle" alt=""></span><span itemprop="name">White Parquet</span></a></li>
		<li  id="menu-item-5109" class="menu-item menu-item-type-taxonomy menu-item-object-couleur-parquet menu-item-5109 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/color/grey/" class="dropdown-item"> <span class="menu-item-img"><img width="60" height="60" src="https://www.designparquet.com/wp-content/uploads/gris.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Grey Parquet</span></a></li>
		<li  id="menu-item-8333" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-8333 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/color/noir-en/" class="dropdown-item"> <span class="menu-item-img"><img width="2048" height="2048" src="https://www.designparquet.com/wp-content/uploads/carbone-1-scaled.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Black parquet</span></a></li>
	</ul>
</li>
	<li  id="menu-item-4101" class="see-all menu-item menu-item-type-post_type_archive menu-item-object-parquet menu-item-has-children dropdown has-megamenu menu-item-4101 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/" class="dropdown-item"><span itemprop="name">SUPPORT</span><span class="see-all-link"> See All</span></a>
	<ul class="megamenu-child-col depth-1" aria-labelledby="menu-item-dropdown-4100">
		<li  id="menu-item-5095" class="menu-item menu-item-type-taxonomy menu-item-object-support-parquet menu-item-5095 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/support/solid-parquet-floor/" class="dropdown-item"> <span class="menu-item-img"><img width="389" height="389" src="https://www.designparquet.com/wp-content/uploads/massif.png" class="rounded-circle" alt=""></span><span itemprop="name">Solid Parquet</span></a></li>
		<li  id="menu-item-5094" class="menu-item menu-item-type-taxonomy menu-item-object-support-parquet menu-item-5094 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/support/semi-solid-loft/" class="dropdown-item"> <span class="menu-item-img"><img width="313" height="313" src="https://www.designparquet.com/wp-content/uploads/loft-semi-massif.png" class="rounded-circle" alt=""></span><span itemprop="name">Semi-solid Parquet Loft Pro</span></a></li>
		<li  id="menu-item-5093" class="menu-item menu-item-type-taxonomy menu-item-object-support-parquet menu-item-5093 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/support/contrecolle-loft/" class="dropdown-item"> <span class="menu-item-img"><img width="377" height="377" src="https://www.designparquet.com/wp-content/uploads/loft-contrecolle.png" class="rounded-circle" alt=""></span><span itemprop="name">Engineered Parquet Loft</span></a></li>
		<li  id="menu-item-5092" class="menu-item menu-item-type-taxonomy menu-item-object-support-parquet menu-item-5092 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/support/decking/" class="dropdown-item"> <span class="menu-item-img"><img width="72" height="72" src="https://www.designparquet.com/wp-content/uploads/terrasse.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Decking blade</span></a></li>
		<li  id="menu-item-5091" class="menu-item menu-item-type-taxonomy menu-item-object-support-parquet menu-item-5091 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/support/bathroom-parquet/" class="dropdown-item"> <span class="menu-item-img"><img width="581" height="581" src="https://www.designparquet.com/wp-content/uploads/navylam-teck-pre-huile-natura-15x126-zoom1-1-scaled-e1691654765958.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Bathroom Parquet</span></a></li>
	</ul>
</li>
	<li  id="menu-item-4103" class="see-all two-col menu-item menu-item-type-post_type_archive menu-item-object-parquet menu-item-has-children dropdown has-megamenu menu-item-4103 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/" class="dropdown-item"><span itemprop="name">SPECIES</span><span class="see-all-link"> See All</span></a>
	<ul class="megamenu-child-col depth-1" aria-labelledby="menu-item-dropdown-4100">
		<li  id="menu-item-5096" class="menu-item menu-item-type-taxonomy menu-item-object-essence-parquet menu-item-5096 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/species/oak/" class="dropdown-item"> <span class="menu-item-img"><img width="50" height="47" src="https://www.designparquet.com/wp-content/uploads/chene.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Oak</span></a></li>
		<li  id="menu-item-5097" class="menu-item menu-item-type-taxonomy menu-item-object-essence-parquet menu-item-5097 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/species/teak/" class="dropdown-item"> <span class="menu-item-img"><img width="60" height="60" src="https://www.designparquet.com/wp-content/uploads/teck.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Teak</span></a></li>
		<li  id="menu-item-5098" class="menu-item menu-item-type-taxonomy menu-item-object-essence-parquet menu-item-5098 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/species/acacia/" class="dropdown-item"> <span class="menu-item-img"><img width="50" height="48" src="https://www.designparquet.com/wp-content/uploads/acacia.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Acacia</span></a></li>
		<li  id="menu-item-5165" class="menu-item menu-item-type-taxonomy menu-item-object-essence-parquet menu-item-5165 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/species/jatoba/" class="dropdown-item"> <span class="menu-item-img"><img width="60" height="60" src="https://www.designparquet.com/wp-content/uploads/jatoba.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Jatoba</span></a></li>
		<li  id="menu-item-5100" class="menu-item menu-item-type-taxonomy menu-item-object-essence-parquet menu-item-5100 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/species/ash/" class="dropdown-item"> <span class="menu-item-img"><img width="60" height="60" src="https://www.designparquet.com/wp-content/uploads/noyer.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Ash</span></a></li>
		<li  id="menu-item-5101" class="menu-item menu-item-type-taxonomy menu-item-object-essence-parquet menu-item-5101 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/species/merbau/" class="dropdown-item"> <span class="menu-item-img"><img width="60" height="60" src="https://www.designparquet.com/wp-content/uploads/merbau.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Merbau</span></a></li>
		<li  id="menu-item-5102" class="menu-item menu-item-type-taxonomy menu-item-object-essence-parquet menu-item-5102 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/species/wenge/" class="dropdown-item"> <span class="menu-item-img"><img width="60" height="60" src="https://www.designparquet.com/wp-content/uploads/wenge.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Wenge</span></a></li>
		<li  id="menu-item-5103" class="menu-item menu-item-type-taxonomy menu-item-object-essence-parquet menu-item-5103 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/species/doussie/" class="dropdown-item"> <span class="menu-item-img"><img width="60" height="60" src="https://www.designparquet.com/wp-content/uploads/doussie.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Doussie</span></a></li>
		<li  id="menu-item-5104" class="menu-item menu-item-type-taxonomy menu-item-object-essence-parquet menu-item-5104 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/species/walnut/" class="dropdown-item"> <span class="menu-item-img"><img width="499" height="499" src="https://www.designparquet.com/wp-content/uploads/noyer-walnut-min-menu.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Walnut</span></a></li>
		<li  id="menu-item-5105" class="menu-item menu-item-type-taxonomy menu-item-object-essence-parquet menu-item-5105 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/species/ipe/" class="dropdown-item"> <span class="menu-item-img"><img width="60" height="60" src="https://www.designparquet.com/wp-content/uploads/ipe.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Ipe</span></a></li>
		<li  id="menu-item-7958" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-7958 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/species/afrormosia/" class="dropdown-item"> <span class="menu-item-img"><img width="5412" height="723" src="https://www.designparquet.com/wp-content/uploads/afrormosia-copie.png" class="rounded-circle" alt=""></span><span itemprop="name">Afrormosia</span></a></li>
		<li  id="menu-item-7959" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-7959 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/species/purpleheart/" class="dropdown-item"> <span class="menu-item-img"><img width="1536" height="2048" src="https://www.designparquet.com/wp-content/uploads/amarante-lp-na-16180-2ch-vsat-zoom-scaled.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Purpleheard</span></a></li>
		<li  id="menu-item-7960" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-7960 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/species/cabreuva/" class="dropdown-item"> <span class="menu-item-img"><img width="2000" height="2000" src="https://www.designparquet.com/wp-content/uploads/cabreuva-loft-ru-ssch-e-frises.png" class="rounded-circle" alt=""></span><span itemprop="name">Cabreuva</span></a></li>
		<li  id="menu-item-7961" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-7961 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/species/maple/" class="dropdown-item"> <span class="menu-item-img"><img width="1710" height="234" src="https://www.designparquet.com/wp-content/uploads/erable-vernis-plinthe.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Maple</span></a></li>
		<li  id="menu-item-7963" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-7963 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/species/iroko/" class="dropdown-item"> <span class="menu-item-img"><img width="1429" height="302" src="https://www.designparquet.com/wp-content/uploads/iroko-vernis-plinthe.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Iroko</span></a></li>
		<li  id="menu-item-7964" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-7964 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/species/padouk/" class="dropdown-item"> <span class="menu-item-img"><img width="1329" height="1516" src="https://www.designparquet.com/wp-content/uploads/padouk-zoom.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Padouk</span></a></li>
		<li  id="menu-item-7965" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-7965 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/species/cumaru/" class="dropdown-item"> <span class="menu-item-img"><img width="768" height="1024" src="https://www.designparquet.com/wp-content/uploads/cumaru-15120300-1200-4ch-vernis-satine-fichier-web-1-e1691736325973.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Cumaru</span></a></li>
	</ul>
</li>
	<li  id="menu-item-4106" class="see-all menu-item menu-item-type-post_type_archive menu-item-object-parquet menu-item-has-children dropdown has-megamenu menu-item-4106 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/" class="dropdown-item"><span itemprop="name">PATTERNS</span><span class="see-all-link"> See All</span></a>
	<ul class="megamenu-child-col depth-1" aria-labelledby="menu-item-dropdown-4100">
		<li  id="menu-item-5516" class="menu-item menu-item-type-taxonomy menu-item-object-motif-parquet menu-item-5516 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/pattern/chevron/" class="dropdown-item"> <span class="menu-item-img"><img width="242" height="242" src="https://www.designparquet.com/wp-content/uploads/point-de-hongrie.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Chevron</span></a></li>
		<li  id="menu-item-5116" class="menu-item menu-item-type-taxonomy menu-item-object-motif-parquet menu-item-5116 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/pattern/herringbone/" class="dropdown-item"> <span class="menu-item-img"><img width="239" height="239" src="https://www.designparquet.com/wp-content/uploads/baton-rompu-1.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Herringbone</span></a></li>
		<li  id="menu-item-5119" class="menu-item menu-item-type-taxonomy menu-item-object-motif-parquet menu-item-5119 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/pattern/random-lenghts-strips/" class="dropdown-item"> <span class="menu-item-img"><img width="297" height="297" src="https://www.designparquet.com/wp-content/uploads/anglaise.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Random lenghts strips</span></a></li>
		<li  id="menu-item-5112" class="d-none menu-item menu-item-type-taxonomy menu-item-object-motif-parquet menu-item-5112 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/pattern/brick-pattern/" class="dropdown-item"> <span class="menu-item-img"><img width="302" height="306" src="https://www.designparquet.com/wp-content/uploads/coupe-de-pierre-1.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Brick pattern</span></a></li>
		<li  id="menu-item-5115" class="menu-item menu-item-type-taxonomy menu-item-object-motif-parquet menu-item-5115 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/pattern/french-style-3-widths/" class="dropdown-item"> <span class="menu-item-img"><img width="282" height="282" src="https://www.designparquet.com/wp-content/uploads/a-la-francaise.jpg" class="rounded-circle" alt=""></span><span itemprop="name">French style (3 widths)</span></a></li>
		<li  id="menu-item-5118" class="menu-item menu-item-type-taxonomy menu-item-object-motif-parquet menu-item-5118 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/pattern/panels/" class="dropdown-item"> <span class="menu-item-img"><img width="288" height="288" src="https://www.designparquet.com/wp-content/uploads/panneaux-versailles-1.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Panels</span></a></li>
		<li  id="menu-item-5114" class="menu-item menu-item-type-taxonomy menu-item-object-motif-parquet menu-item-5114 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/pattern/custom-made/" class="dropdown-item"> <span class="menu-item-img"><img width="256" height="256" src="https://www.designparquet.com/wp-content/uploads/sur-mesure-1.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Custom-made</span></a></li>
		<li  id="menu-item-7971" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-7971 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/pattern/mosaic/" class="dropdown-item"> <span class="menu-item-img"><img width="1904" height="1892" src="https://www.designparquet.com/wp-content/uploads/parquet-mosaiques.png" class="rounded-circle" alt=""></span><span itemprop="name">Mosaic</span></a></li>
	</ul>
</li>
	<li  id="menu-item-4107" class="see-all d-none menu-item menu-item-type-post_type_archive menu-item-object-parquet menu-item-has-children dropdown has-megamenu menu-item-4107 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/" class="dropdown-item"><span itemprop="name">SIZES</span><span class="see-all-link"> See All</span></a>
	<ul class="megamenu-child-col depth-1" aria-labelledby="menu-item-dropdown-4100">
		<li  id="menu-item-5123" class="menu-item menu-item-type-taxonomy menu-item-object-largeur-parquet menu-item-5123 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/width/m-140-en/" class="dropdown-item"><span itemprop="name">M</span></a></li>
		<li  id="menu-item-5122" class="menu-item menu-item-type-taxonomy menu-item-object-largeur-parquet menu-item-5122 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/width/l-180-en/" class="dropdown-item"><span itemprop="name">L</span></a></li>
		<li  id="menu-item-5121" class="menu-item menu-item-type-taxonomy menu-item-object-largeur-parquet menu-item-5121 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/width/custom-made/" class="dropdown-item"><span itemprop="name">Custom-made</span></a></li>
	</ul>
</li>
	<li  id="menu-item-4108" class="see-all menu-item menu-item-type-post_type_archive menu-item-object-parquet menu-item-has-children dropdown has-megamenu menu-item-4108 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/" class="dropdown-item"><span itemprop="name">SURFACE ASPECT</span><span class="see-all-link"> See All</span></a>
	<ul class="megamenu-child-col depth-1" aria-labelledby="menu-item-dropdown-4100">
		<li  id="menu-item-5139" class="menu-item menu-item-type-taxonomy menu-item-object-finition-parquet menu-item-5139 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/finishing/unfinished/" class="dropdown-item"> <span class="menu-item-img"><img width="60" height="60" src="https://www.designparquet.com/wp-content/uploads/brut.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Unfinished</span></a></li>
		<li  id="menu-item-5125" class="menu-item menu-item-type-taxonomy menu-item-object-finition-parquet menu-item-5125 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/finishing/brushed/" class="dropdown-item"> <span class="menu-item-img"><img width="60" height="60" src="https://www.designparquet.com/wp-content/uploads/brosse.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Brushed</span></a></li>
		<li  id="menu-item-5130" class="menu-item menu-item-type-taxonomy menu-item-object-finition-parquet menu-item-5130 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/finishing/heavy-brushed/" class="dropdown-item"> <span class="menu-item-img"><img width="60" height="60" src="https://www.designparquet.com/wp-content/uploads/structure.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Heavy Brushed</span></a></li>
		<li  id="menu-item-5129" class="menu-item menu-item-type-taxonomy menu-item-object-finition-parquet menu-item-5129 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/finishing/distressed/" class="dropdown-item"> <span class="menu-item-img"><img width="60" height="60" src="https://www.designparquet.com/wp-content/uploads/vieilli.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Distressed</span></a></li>
		<li  id="menu-item-7986" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-7986 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/collection/high-traffic/" class="dropdown-item"> <span class="menu-item-img"><img width="2048" height="675" src="https://www.designparquet.com/wp-content/uploads/roc-vanille-16-scaled.jpg" class="rounded-circle" alt=""></span><span itemprop="name">High Traffic &#8211; ROC</span></a></li>
		<li  id="menu-item-5515" class="menu-item menu-item-type-post_type_archive menu-item-object-parquet menu-item-5515 nav-item"><a itemprop="url" href="https://dmafloors.com/floors/" class="dropdown-item"> <span class="menu-item-img"><img width="107" height="107" src="https://www.designparquet.com/wp-content/uploads/autres.png" class="rounded-circle" alt=""></span><span itemprop="name">See more</span></a></li>
	</ul>
</li>
</ul>
</li>
<li  id="menu-item-4109" class="menu-item menu-item-type-post_type_archive menu-item-object-accessoire menu-item-has-children dropdown has-megamenu menu-item-4109 nav-item"><a href="#" data-bs-toggle="dropdown" aria-expanded="false" class="dropdown-toggle nav-link" id="menu-item-dropdown-4109"><span itemprop="name">Accessories</span></a>
<ul class="dropdown-menu megamenu depth-0" aria-labelledby="menu-item-dropdown-4109">
	<li  id="menu-item-4110" class="see-all menu-item menu-item-type-post_type_archive menu-item-object-accessoire menu-item-has-children dropdown has-megamenu menu-item-4110 nav-item"><a itemprop="url" href="https://dmafloors.com/accessories/" class="dropdown-item"><span itemprop="name">FINISHING ACCESSORIES</span><span class="see-all-link"> See All</span></a>
	<ul class="megamenu-child-col depth-1" aria-labelledby="menu-item-dropdown-4109">
		<li  id="menu-item-5146" class="menu-item menu-item-type-taxonomy menu-item-object-finition-accessoire menu-item-5146 nav-item"><a itemprop="url" href="https://dmafloors.com/accessories/finishing/solid-skirting-board/" class="dropdown-item"> <span class="menu-item-img"><img width="126" height="126" src="https://www.designparquet.com/wp-content/uploads/plinthe-massive.png" class="rounded-circle" alt=""></span><span itemprop="name">Solid skirting board</span></a></li>
		<li  id="menu-item-5149" class="menu-item menu-item-type-taxonomy menu-item-object-finition-accessoire menu-item-5149 nav-item"><a itemprop="url" href="https://dmafloors.com/accessories/finishing/veneered-skirting-board/" class="dropdown-item"> <span class="menu-item-img"><img width="126" height="126" src="https://www.designparquet.com/wp-content/uploads/plinthe-plaquee.png" class="rounded-circle" alt=""></span><span itemprop="name">Veneered skirting board</span></a></li>
		<li  id="menu-item-5141" class="menu-item menu-item-type-taxonomy menu-item-object-finition-accessoire menu-item-5141 nav-item"><a itemprop="url" href="https://dmafloors.com/accessories/finishing/1-4-round/" class="dropdown-item"> <span class="menu-item-img"><img width="282" height="282" src="https://www.designparquet.com/wp-content/uploads/quart-rond.png" class="rounded-circle" alt=""></span><span itemprop="name">1/4 round</span></a></li>
		<li  id="menu-item-5142" class="menu-item menu-item-type-taxonomy menu-item-object-finition-accessoire menu-item-5142 nav-item"><a itemprop="url" href="https://dmafloors.com/accessories/finishing/cover-strip/" class="dropdown-item"> <span class="menu-item-img"><img width="279" height="278" src="https://www.designparquet.com/wp-content/uploads/champlat.png" class="rounded-circle" alt=""></span><span itemprop="name">Cover strip</span></a></li>
		<li  id="menu-item-5143" class="menu-item menu-item-type-taxonomy menu-item-object-finition-accessoire menu-item-5143 nav-item"><a itemprop="url" href="https://dmafloors.com/accessories/finishing/leveling-joint/" class="dropdown-item"> <span class="menu-item-img"><img width="400" height="399" src="https://www.designparquet.com/wp-content/uploads/seuil-recouvrement.png" class="rounded-circle" alt=""></span><span itemprop="name">Leveling joint</span></a></li>
		<li  id="menu-item-5145" class="menu-item menu-item-type-taxonomy menu-item-object-finition-accessoire menu-item-5145 nav-item"><a itemprop="url" href="https://dmafloors.com/accessories/finishing/s-profile/" class="dropdown-item"> <span class="menu-item-img"><img width="294" height="297" src="https://www.designparquet.com/wp-content/uploads/contre-plinthe.png" class="rounded-circle" alt=""></span><span itemprop="name">S profile</span></a></li>
		<li  id="menu-item-5147" class="menu-item menu-item-type-taxonomy menu-item-object-finition-accessoire menu-item-5147 nav-item"><a itemprop="url" href="https://dmafloors.com/accessories/finishing/stair-nose/" class="dropdown-item"> <span class="menu-item-img"><img width="312" height="310" src="https://www.designparquet.com/wp-content/uploads/nez-marche.png" class="rounded-circle" alt=""></span><span itemprop="name">Stair nose</span></a></li>
		<li  id="menu-item-5148" class="menu-item menu-item-type-taxonomy menu-item-object-finition-accessoire menu-item-5148 nav-item"><a itemprop="url" href="https://dmafloors.com/accessories/finishing/t-joint/" class="dropdown-item"> <span class="menu-item-img"><img width="374" height="374" src="https://www.designparquet.com/wp-content/uploads/seuil-t.png" class="rounded-circle" alt=""></span><span itemprop="name">T joint</span></a></li>
	</ul>
</li>
	<li  id="menu-item-4111" class="see-all menu-item menu-item-type-post_type_archive menu-item-object-accessoire menu-item-has-children dropdown has-megamenu menu-item-4111 nav-item"><a itemprop="url" href="https://dmafloors.com/accessories/" class="dropdown-item"><span itemprop="name">STAIRCASE COVER</span><span class="see-all-link"> See All</span></a>
	<ul class="megamenu-child-col depth-1" aria-labelledby="menu-item-dropdown-4109">
		<li  id="menu-item-5150" class="menu-item menu-item-type-taxonomy menu-item-object-marche-accessoire menu-item-5150 nav-item"><a itemprop="url" href="https://dmafloors.com/accessories/stair/stairs/" class="dropdown-item"> <span class="menu-item-img"><img width="558" height="558" src="https://www.designparquet.com/wp-content/uploads/marches.png" class="rounded-circle" alt=""></span><span itemprop="name">Stairs</span></a></li>
		<li  id="menu-item-5151" class="menu-item menu-item-type-taxonomy menu-item-object-marche-accessoire menu-item-5151 nav-item"><a itemprop="url" href="https://dmafloors.com/accessories/stair/up-risers/" class="dropdown-item"> <span class="menu-item-img"><img width="558" height="558" src="https://www.designparquet.com/wp-content/uploads/contre-marches.png" class="rounded-circle" alt=""></span><span itemprop="name">Up-risers</span></a></li>
	</ul>
</li>
	<li  id="menu-item-4112" class="see-all menu-item menu-item-type-post_type_archive menu-item-object-accessoire menu-item-has-children dropdown has-megamenu menu-item-4112 nav-item"><a itemprop="url" href="https://dmafloors.com/accessories/" class="dropdown-item"><span itemprop="name">LAYING ACCESSORIES</span><span class="see-all-link"> See All</span></a>
	<ul class="megamenu-child-col depth-1" aria-labelledby="menu-item-dropdown-4109">
		<li  id="menu-item-5154" class="menu-item menu-item-type-taxonomy menu-item-object-pose-accessoire menu-item-5154 nav-item"><a itemprop="url" href="https://dmafloors.com/accessories/laying/glues/" class="dropdown-item"> <span class="menu-item-img"><img width="180" height="150" src="https://www.designparquet.com/wp-content/uploads/colles-bucket-878351.png" class="rounded-circle" alt=""></span><span itemprop="name">Glues</span></a></li>
		<li  id="menu-item-5156" class="menu-item menu-item-type-taxonomy menu-item-object-pose-accessoire menu-item-5156 nav-item"><a itemprop="url" href="https://dmafloors.com/accessories/laying/underlayers/" class="dropdown-item"> <span class="menu-item-img"><img width="1372" height="1372" src="https://www.designparquet.com/wp-content/uploads/sous-couche.png" class="rounded-circle" alt=""></span><span itemprop="name">Underlayers</span></a></li>
	</ul>
</li>
	<li  id="menu-item-4113" class="see-all menu-item menu-item-type-post_type_archive menu-item-object-accessoire menu-item-has-children dropdown has-megamenu menu-item-4113 nav-item"><a itemprop="url" href="https://dmafloors.com/accessories/" class="dropdown-item"><span itemprop="name">FLOOR MAINTENANCE</span><span class="see-all-link"> See All</span></a>
	<ul class="megamenu-child-col depth-1" aria-labelledby="menu-item-dropdown-4109">
		<li  id="menu-item-5158" class="menu-item menu-item-type-taxonomy menu-item-object-entretien-parquets menu-item-5158 nav-item"><a itemprop="url" href="https://dmafloors.com/accessories/maintenance/oil/" class="dropdown-item"> <span class="menu-item-img"><img width="97" height="154" src="https://www.designparquet.com/wp-content/uploads/huile-noun-water-bottle-1126380.png" class="rounded-circle" alt=""></span><span itemprop="name">Oil</span></a></li>
		<li  id="menu-item-5157" class="menu-item menu-item-type-taxonomy menu-item-object-entretien-parquets menu-item-5157 nav-item"><a itemprop="url" href="https://dmafloors.com/accessories/maintenance/cleaner/" class="dropdown-item"> <span class="menu-item-img"><img width="600" height="600" src="https://www.designparquet.com/wp-content/uploads/accessoire-nettoyant-l.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Cleaner</span></a></li>
		<li  id="menu-item-5159" class="menu-item menu-item-type-taxonomy menu-item-object-entretien-parquets menu-item-5159 nav-item"><a itemprop="url" href="https://dmafloors.com/accessories/maintenance/renovator/" class="dropdown-item"> <span class="menu-item-img"><img width="600" height="600" src="https://www.designparquet.com/wp-content/uploads/renovateur-designparquet.jpg" class="rounded-circle" alt=""></span><span itemprop="name">Renovator</span></a></li>
	</ul>
</li>
</ul>
</li>
<li  id="menu-item-8033" class="one-col menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children dropdown has-megamenu menu-item-8033 nav-item"><a href="#" data-bs-toggle="dropdown" aria-expanded="false" class="dropdown-toggle nav-link" id="menu-item-dropdown-8033"><span itemprop="name">Advice</span></a>
<ul class="dropdown-menu megamenu depth-0" aria-labelledby="menu-item-dropdown-8033">
	<li  id="menu-item-8030" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-8030 nav-item"><a itemprop="url" href="https://dmafloors.com/blog/categorie/choosing-your-parquet/" class="dropdown-item"><span itemprop="name">Choosing your parquet</span><span class="see-all-link"> See All</span></a></li>
	<li  id="menu-item-8032" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-8032 nav-item"><a itemprop="url" href="https://dmafloors.com/blog/categorie/maintaining-your-parquet/" class="dropdown-item"><span itemprop="name">Maintaining your parquet</span><span class="see-all-link"> See All</span></a></li>
	<li  id="menu-item-8031" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-8031 nav-item"><a itemprop="url" href="https://dmafloors.com/blog/categorie/technical-advice/" class="dropdown-item"><span itemprop="name">Technical Advice</span><span class="see-all-link"> See All</span></a></li>
</ul>
</li>
<li  id="menu-item-5453" class="one-col menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children dropdown has-megamenu menu-item-5453 nav-item"><a href="#" data-bs-toggle="dropdown" aria-expanded="false" class="dropdown-toggle nav-link" id="menu-item-dropdown-5453"><span itemprop="name">About us</span></a>
<ul class="dropdown-menu megamenu depth-0" aria-labelledby="menu-item-dropdown-5453">
	<li  id="menu-item-7712" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7712 nav-item"><a itemprop="url" href="https://dmafloors.com/about-us/" class="dropdown-item"><span itemprop="name">About us</span><span class="see-all-link"> See All</span></a></li>
	<li  id="menu-item-7994" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-7994 nav-item"><a itemprop="url" href="https://dmafloors.com/our-commitments/" class="dropdown-item"><span itemprop="name">Our commitments</span><span class="see-all-link"> See All</span></a></li>
	<li  id="menu-item-7713" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-7713 nav-item"><a itemprop="url" href="https://dmafloors.com/blog/categorie/prestigious-projects/" class="dropdown-item"><span itemprop="name">Prestigious projects</span><span class="see-all-link"> See All</span></a></li>
	<li  id="menu-item-7711" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7711 nav-item"><a itemprop="url" href="https://dmafloors.com/careers/" class="dropdown-item"><span itemprop="name">Careers</span><span class="see-all-link"> See All</span></a></li>
</ul>
</li>
<li  id="menu-item-5251" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5251 nav-item"><a itemprop="url" href="https://dmafloors.com/price-request/" class="nav-link"><span itemprop="name">Price request</span></a></li>
</ul></div>                </div> <!-- container.// -->
            </nav>
            
            <div class="d-flex d-md-none mobile-nav">
                <div class="mobile-nav-preheader">
                    <div class="item-search">
                        <a href="#"><img width="13" height="16" src="https://www.designparquet.com/wp-content/themes/designparquet/dist/img/icon-search-dark.svg" alt="icon recherche" class="icon-recherche" /></a>
                    </div>
                    <select id="lang_dropdown" name="" onchange="javascript:location.href = this.value;"><option value="https://www.designparquet.com/" >FR</option><option value="https://dmafloors.com/" selected="selected">EN</option></select>                    <a href="https://dmafloors.com/contact-us/"><img width="17" height="13" src="https://www.designparquet.com/wp-content/themes/designparquet/dist/img/icon-mail.svg" alt="icon mail" class="icon-mail" /></a>
                </div>
                <input type="checkbox" id="hamburger1" />
                <label for="hamburger1"></label>
                <ul id="mobile-menu" class="mobile-nav-links d-flex d-md-none" itemscope itemtype="http://www.schema.org/SiteNavigationElement"><li id="menu-item-3962" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-2183 current_page_item menu-item-3962"><a href="https://dmafloors.com/" aria-current="page">French manufacturer of standard and custom-made parquet flooring</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5251"><a href="https://dmafloors.com/price-request/">Price request</a></li>
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7712"><a href="https://dmafloors.com/about-us/">About us</a></li>
</ul>            </div>
    </div>
    </header><!-- #masthead -->